platform :ios, '9.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :git => 'https://github.com/adri4silva/MessageKit.git'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end
